spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/${security.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

security:
  unprotected-endpoints: v3/api-docs/**, /swagger-ui/**, /actuator/**
  realm: demo

server.port: 8081